[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/segmentio/kafka-go"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~0.8.0"
